"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 17:42:32.795845
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('closed_at', app.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_accounts_is_active'), ['is_active'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_at'), ['at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('trade_uid', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_code'), ['code'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('tv_trade_id', sa.String(length=128), nullable=True),
    sa.Column('signal_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('received_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('processing_started_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('processed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_code', sa.String(length=64), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_snapshots_at'), ['at'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_uid', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('paper_account_id', sa.Integer(), nullable=True),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('exit_event_id', sa.String(length=128), nullable=True),
    sa.Column('tv_trade_id', sa.String(length=128), nullable=True),
    sa.Column('futures_symbol', sa.String(length=64), nullable=False),
    sa.Column('futures_root', sa.String(length=16), nullable=False),
    sa.Column('futures_direction', sa.String(length=8), nullable=False),
    sa.Column('futures_entry', sa.Float(), nullable=True),
    sa.Column('futures_stop', sa.Float(), nullable=True),
    sa.Column('futures_target', sa.Float(), nullable=True),
    sa.Column('futures_exit', sa.Float(), nullable=True),
    sa.Column('risk_points', sa.Float(), nullable=True),
    sa.Column('signal_type', sa.String(length=64), nullable=True),
    sa.Column('option_underlying', sa.String(length=16), nullable=True),
    sa.Column('underlying_price_at_signal', sa.Float(), nullable=True),
    sa.Column('contract_id', sa.String(length=128), nullable=True),
    sa.Column('option_symbol', sa.String(length=64), nullable=True),
    sa.Column('option_type', sa.String(length=4), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('expiration_mode', sa.String(length=32), nullable=True),
    sa.Column('strike_mode', sa.String(length=32), nullable=True),
    sa.Column('sizing_mode', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_bid', sa.Float(), nullable=True),
    sa.Column('entry_ask', sa.Float(), nullable=True),
    sa.Column('entry_mid', sa.Float(), nullable=True),
    sa.Column('entry_quote_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('entry_slippage', sa.Float(), nullable=True),
    sa.Column('entry_fill', sa.Float(), nullable=True),
    sa.Column('entry_timestamp', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_bid', sa.Float(), nullable=True),
    sa.Column('exit_ask', sa.Float(), nullable=True),
    sa.Column('exit_mid', sa.Float(), nullable=True),
    sa.Column('exit_quote_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_slippage', sa.Float(), nullable=True),
    sa.Column('exit_fill', sa.Float(), nullable=True),
    sa.Column('exit_timestamp', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('gross_cost', sa.Float(), nullable=True),
    sa.Column('gross_proceeds', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('return_percent', sa.Float(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('current_ask', sa.Float(), nullable=True),
    sa.Column('current_quote_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('signal_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('webhook_received_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('contract_selected_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('execution_requested_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_signal_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_received_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('broker_account_ref', sa.String(length=128), nullable=True),
    sa.Column('reject_code', sa.String(length=64), nullable=True),
    sa.Column('reject_message', sa.Text(), nullable=True),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('selection_notes', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('closed_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_uid')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_exit_event_id'), ['exit_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_tv_trade_id'), ['tv_trade_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('bid_at_request', sa.Float(), nullable=True),
    sa.Column('ask_at_request', sa.Float(), nullable=True),
    sa.Column('mid_at_request', sa.Float(), nullable=True),
    sa.Column('quote_time', app.db.UTCDateTime(), nullable=True),
    sa.Column('slippage_assumption', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('broker_account_ref', sa.String(length=128), nullable=True),
    sa.Column('cancel_status', sa.String(length=24), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('submitted_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('filled_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trade_id'), ['trade_id'], unique=False)

    op.create_table('paper_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_ledger_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_ledger_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_state_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_state_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_state_transitions_trade_id'), ['trade_id'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('trade_state_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_state_transitions_trade_id'))

    op.drop_table('trade_state_transitions')
    with op.batch_alter_table('paper_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_ledger_trade_id'))
        batch_op.drop_index(batch_op.f('ix_paper_ledger_account_id'))

    op.drop_table('paper_ledger')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_trade_id'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_tv_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trades_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trades_state'))
        batch_op.drop_index(batch_op.f('ix_trades_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_trades_mode'))
        batch_op.drop_index(batch_op.f('ix_trades_exit_event_id'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))
        batch_op.drop_index(batch_op.f('ix_trades_closed_at'))

    op.drop_table('trades')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_at'))
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_account_id'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_received_at'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_code'))
        batch_op.drop_index(batch_op.f('ix_system_events_at'))

    op.drop_table('system_events')
    op.drop_table('strategies')
    op.drop_table('settings')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_at'))

    op.drop_table('risk_events')
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_accounts_is_active'))

    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
